"Traceback (most recent call last):
  File ""c:\Users\shahz\OneDrive\Desktop\TheMoment\The-moment-parcer\main.py"", line 56, in <module>
    post_data(title[0].text, text[0].text, img['src'])
AttributeError: 'str' object has no attribute 'text'

";date: <built-in method now of type object at 0x00007FFA54F10CD0>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    post_data(title[0].text, text, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 371, in prepare
    self.prepare_body(data, files, json)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 234, in dumps
    return cls(
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBAE604650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    post_data(title[0].text, text, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 371, in prepare
    self.prepare_body(data, files, json)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 234, in dumps
    return cls(
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBAE604650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 58, in <module>
    post_data(title[0].text, content, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 371, in prepare
    self.prepare_body(data, files, json)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 234, in dumps
    return cls(
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 57, in <module>
    post_data(title[0].text, content, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 371, in prepare
    self.prepare_body(data, files, json)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 234, in dumps
    return cls(
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 57, in <module>
    post_data(title[0].text, content, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 371, in prepare
    self.prepare_body(data, files, json)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 234, in dumps
    return cls(
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 57, in <module>
    post_data(title[0].text, content, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 19, in post_data
    'content' : dumps(content),
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 231, in dumps
    return _default_encoder.encode(obj)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 57, in <module>
    post_data(title[0].text, content, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 19, in post_data
    'content' : dumps(list(content)),
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 231, in dumps
    return _default_encoder.encode(obj)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 57, in <module>
    post_data(title[0].text, content, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 371, in prepare
    self.prepare_body(data, files, json)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 234, in dumps
    return cls(
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 52, in <module>
    content[tag].remove(tag)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\bs4\element.py"", line 1519, in __getitem__
    return self.attrs[key]
KeyError: <p><span itemprop=""image"" itemscope="""" itemtype=""https://schema.org/ImageObject""><img alt="""" class=""size-full wp-image-4771 aligncenter"" height=""459"" itemprop=""url image"" loading=""lazy"" sizes=""(max-width: 800px) 100vw, 800px"" src=""http://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg.jpg"" srcset=""https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg.jpg 800w, https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg-300x172.jpg 300w, https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg-768x441.jpg 768w"" width=""800""/><meta content=""800"" itemprop=""width""/><meta content=""459"" itemprop=""height""/></span></p>

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 52, in <module>
    content[tag].remove(tag)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\bs4\element.py"", line 1519, in __getitem__
    return self.attrs[key]
KeyError: <p><span itemprop=""image"" itemscope="""" itemtype=""https://schema.org/ImageObject""><img alt="""" class=""size-full wp-image-4771 aligncenter"" height=""459"" itemprop=""url image"" loading=""lazy"" sizes=""(max-width: 800px) 100vw, 800px"" src=""http://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg.jpg"" srcset=""https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg.jpg 800w, https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg-300x172.jpg 300w, https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg-768x441.jpg 768w"" width=""800""/><meta content=""800"" itemprop=""width""/><meta content=""459"" itemprop=""height""/></span></p>

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 53, in <module>
    content[tag].remove(tag)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\bs4\element.py"", line 1519, in __getitem__
    return self.attrs[key]
KeyError: <p><span itemprop=""image"" itemscope="""" itemtype=""https://schema.org/ImageObject""><img alt="""" class=""size-full wp-image-4771 aligncenter"" height=""459"" itemprop=""url image"" loading=""lazy"" sizes=""(max-width: 800px) 100vw, 800px"" src=""http://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg.jpg"" srcset=""https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg.jpg 800w, https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg-300x172.jpg 300w, https://the-moment.ru/wp-content/uploads/2017/10/xranenie-deneg-768x441.jpg 768w"" width=""800""/><meta content=""800"" itemprop=""width""/><meta content=""459"" itemprop=""height""/></span></p>

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 53, in <module>
    content.remove(tag)
TypeError: 'NoneType' object is not callable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 54, in <module>
    content.remove[tag]
TypeError: 'builtin_function_or_method' object is not subscriptable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 54, in <module>
    content.remove[tag]
TypeError: 'builtin_function_or_method' object is not subscriptable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 65, in <module>
    post_data(title[0].text, content, img['src'])
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 573, in request
    prep = self.prepare_request(req)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\sessions.py"", line 484, in prepare_request
    p.prepare(
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 371, in prepare
    self.prepare_body(data, files, json)
  File ""C:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\venv\lib\site-packages\requests\models.py"", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\__init__.py"", line 234, in dumps
    return cls(
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 257, in iterencode
    return _iterencode(o, 0)
  File ""C:\Users\shahzod.ravshanov\AppData\Local\Programs\Python\Python39\lib\json\encoder.py"", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tag is not JSON serializable

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 65, in <module>
    post_data(title[0].text, """".join(content), img['src'])
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    print("""".join(content))
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    print("""".join(content.encode('UTF8')))
AttributeError: 'list' object has no attribute 'encode'

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    print("""".join(content))
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    print("""".join(content))
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    print("""".join(content))
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 56, in <module>
    print(""{}"".join(content)) # пытаюсь запихнуть все данные в списке в строку но выдаёт ошибку
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahzod.ravshanov\Desktop\Projects\Parcer\The-moment-parcer\main.py"", line 57, in <module>
    print(""{}"".join(content)) # пытаюсь запихнуть все данные в списке в строку но выдаёт ошибку
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FFBD0AF4650>

"Traceback (most recent call last):
  File ""c:\Users\shahz\OneDrive\Desktop\TheMoment\The-moment-parcer\main.py"", line 59, in <module>
    print("""".join(content)) # пытаюсь запихнуть все данные в списке в строку но выдаёт ошибку
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FF806170CD0>

"Traceback (most recent call last):
  File ""c:\Users\shahz\OneDrive\Desktop\TheMoment\The-moment-parcer\main.py"", line 59, in <module>
    print("""".join(content)) # пытаюсь запихнуть все данные в списке в строку но выдаёт ошибку
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FF806170CD0>

"Traceback (most recent call last):
  File ""c:\Users\shahz\OneDrive\Desktop\TheMoment\The-moment-parcer\main.py"", line 59, in <module>
    print("""".join(content)) # пытаюсь запихнуть все данные в списке в строку но выдаёт ошибку
TypeError: sequence item 1: expected str instance, Tag found

";date: <built-in method now of type object at 0x00007FF806170CD0>

"Traceback (most recent call last):
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\util\connection.py"", line 95, in create_connection
    raise err
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\util\connection.py"", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\connectionpool.py"", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\connection.py"", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File ""C:\Users\shahz\AppData\Local\Programs\Python\Python310\lib\http\client.py"", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File ""C:\Users\shahz\AppData\Local\Programs\Python\Python310\lib\http\client.py"", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File ""C:\Users\shahz\AppData\Local\Programs\Python\Python310\lib\http\client.py"", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File ""C:\Users\shahz\AppData\Local\Programs\Python\Python310\lib\http\client.py"", line 1037, in _send_output
    self.send(msg)
  File ""C:\Users\shahz\AppData\Local\Programs\Python\Python310\lib\http\client.py"", line 975, in send
    self.connect()
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\connection.py"", line 205, in connect
    conn = self._new_conn()
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\connection.py"", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000174B68260B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\requests\adapters.py"", line 489, in send
    resp = conn.urlopen(
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\urllib3\util\retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174B68260B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""c:\Users\shahz\OneDrive\Desktop\TheMoment\The-moment-parcer\main.py"", line 64, in <module>
    post_data(title[0].text, """".join(clean_content), img['src'])
  File ""c:\Users\shahz\OneDrive\Desktop\TheMoment\The-moment-parcer\main.py"", line 23, in post_data
    response = requests.post(link, json=data)
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\requests\api.py"", line 115, in post
    return request(""post"", url, data=data, json=json, **kwargs)
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\requests\api.py"", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\requests\sessions.py"", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\requests\sessions.py"", line 701, in send
    r = adapter.send(request, **kwargs)
  File ""C:\Users\shahz\OneDrive\Desktop\TheMoment\venv\lib\site-packages\requests\adapters.py"", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000174B68260B0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение'))

";date: <built-in method now of type object at 0x00007FFFBEA40CD0>

